server:
    port: 8080
    context-path: /springboot

logging:
    level:
        tk.mybatis: DEBUG

spring:
    datasource:
#        url: jdbc:sqlserver://192.168.16.200:1433;DatabaseName=test
#        username: root
#        password: 123456
#        # \u4f7f\u7528druid\u6570\u636e\u6e90
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: 123456
        # \u4f7f\u7528druid\u6570\u636e\u6e90
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request

#\u4ee5\u4e0b\u5c5e\u6027\u4e0d\u53ef\u7528
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: tk.mybatis.springboot.util.MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper

#\u914d\u7f6e\u6587\u4ef6\u7684\u8def\u5f84
#mybatis.config\uff1amybatis-config.xml
#\u626b\u63cftypeHandlers\u7684\u5305
#mybatis.typeHandlersPackage\uff1a
#\u68c0\u67e5\u914d\u7f6e\u6587\u4ef6\u662f\u5426\u5b58\u5728
#mybatis.checkConfigLocation\uff1a
#\u8bbe\u7f6e\u6267\u884c\u6a21\u5f0f\uff08SIMPLE, REUSE, BATCH\uff09\uff0c\u9ed8\u8ba4\u4e3aSIMPLE
#mybatis.executorType\uff1aSIMPLE